import { getDatabase } from '../db';
import { TournamentHistory } from '../../shared/schemas';

export const tournamentHistoryRepository = {
    /**
     * Add a tournament history entry
     */
    addHistory: (data: Omit<TournamentHistory, 'id' | 'created_at'>): TournamentHistory => {
        const db = getDatabase();
        const stmt = db.prepare(`
            INSERT INTO tournament_history (
                athlete_id, tournament_id, tournament_name, tournament_date,
                tournament_location, weight_class, age_category, is_auto_generated
            )
            VALUES (
                @athlete_id, @tournament_id, @tournament_name, @tournament_date,
                @tournament_location, @weight_class, @age_category, @is_auto_generated
            )
        `);

        const info = stmt.run({
            athlete_id: data.athlete_id,
            tournament_id: data.tournament_id || null,
            tournament_name: data.tournament_name,
            tournament_date: data.tournament_date,
            tournament_location: data.tournament_location || null,
            weight_class: data.weight_class || null,
            age_category: data.age_category || null,
            is_auto_generated: data.is_auto_generated ? 1 : 0,
        });

        return {
            ...data,
            id: Number(info.lastInsertRowid),
            created_at: new Date().toISOString(),
        };
    },

    /**
     * Get all tournament history for an athlete, ordered by date DESC
     */
    getHistoryByAthlete: (athleteId: number): TournamentHistory[] => {
        const db = getDatabase();
        const stmt = db.prepare(`
            SELECT * FROM tournament_history
            WHERE athlete_id = ?
            ORDER BY tournament_date DESC, created_at DESC
        `);

        const rows = stmt.all(athleteId) as any[];
        return rows.map(row => ({
            ...row,
            is_auto_generated: Boolean(row.is_auto_generated),
        }));
    },

    /**
     * Delete a specific history entry (validates it's not auto-generated)
     */
    deleteHistory: (id: number): boolean => {
        const db = getDatabase();
        // Only allow deletion of manual entries
        const stmt = db.prepare(`
            DELETE FROM tournament_history
            WHERE id = ? AND is_auto_generated = 0
        `);

        const info = stmt.run(id);
        return info.changes > 0;
    },

    /**
     * Delete auto-generated history entry for a specific tournament and athlete
     */
    deleteAutoGeneratedByTournamentAndAthlete: (tournamentId: number, athleteId: number): boolean => {
        const db = getDatabase();
        const stmt = db.prepare(`
            DELETE FROM tournament_history
            WHERE tournament_id = ? AND athlete_id = ? AND is_auto_generated = 1
        `);

        const info = stmt.run(tournamentId, athleteId);
        return info.changes > 0;
    },

    /**
     * Update a manual history entry (validates it's not auto-generated)
     */
    updateHistory: (id: number, data: Partial<Omit<TournamentHistory, 'id' | 'athlete_id' | 'is_auto_generated' | 'created_at'>>): boolean => {
        const db = getDatabase();

        // Build dynamic update query
        const fields: string[] = [];
        const values: any = { id };

        if (data.tournament_name !== undefined) {
            fields.push('tournament_name = @tournament_name');
            values.tournament_name = data.tournament_name;
        }
        if (data.tournament_date !== undefined) {
            fields.push('tournament_date = @tournament_date');
            values.tournament_date = data.tournament_date;
        }
        if (data.tournament_location !== undefined) {
            fields.push('tournament_location = @tournament_location');
            values.tournament_location = data.tournament_location;
        }
        if (data.weight_class !== undefined) {
            fields.push('weight_class = @weight_class');
            values.weight_class = data.weight_class;
        }
        if (data.age_category !== undefined) {
            fields.push('age_category = @age_category');
            values.age_category = data.age_category;
        }

        if (fields.length === 0) {
            return false; // Nothing to update
        }

        const stmt = db.prepare(`
            UPDATE tournament_history
            SET ${fields.join(', ')}
            WHERE id = @id AND is_auto_generated = 0
        `);

        const info = stmt.run(values);
        return info.changes > 0;
    },
};
