import React, { useState, useEffect } from 'react';
import { Plus, Calendar, MapPin, Award, Edit2, Trash2, X } from 'lucide-react';
import { useTournamentHistoryStore } from './useTournamentHistoryStore';
import { TournamentHistory } from '../../../shared/schemas';
import { AddTournamentHistoryModal } from './AddTournamentHistoryModal';

interface TournamentHistoryTimelineProps {
    athleteId: number;
}

export const TournamentHistoryTimeline: React.FC<TournamentHistoryTimelineProps> = ({ athleteId }) => {
    const { history, isLoading, error, loadHistory, deleteHistory } = useTournamentHistoryStore();
    const [isAddingManual, setIsAddingManual] = useState(false);
    const [editingEntry, setEditingEntry] = useState<TournamentHistory | null>(null);

    useEffect(() => {
        loadHistory(athleteId);
    }, [athleteId, loadHistory]);

    const handleDelete = async (id: number, isAutoGenerated: boolean) => {
        if (isAutoGenerated) {
            alert('Auto-generated tournament history entries cannot be deleted manually. Remove the athlete from the tournament roster instead.');
            return;
        }

        if (window.confirm('Are you sure you want to delete this tournament history entry? This action cannot be undone.')) {
            await deleteHistory(id);
        }
    };

    const handleEdit = (entry: TournamentHistory) => {
        if (entry.is_auto_generated) {
            alert('Auto-generated tournament history entries cannot be edited.');
            return;
        }
        setEditingEntry(entry);
    };

    if (isLoading && history.length === 0) {
        return (
            <div className="space-y-4 animate-pulse p-4">
                <div className="h-8 bg-slate-100 rounded w-1/3 mb-4"></div>
                <div className="h-16 bg-slate-100 rounded w-full"></div>
                <div className="h-16 bg-slate-100 rounded w-full"></div>
            </div>
        );
    }

    if (error && history.length === 0) {
        return (
            <div className="p-4 bg-red-50 text-red-600 text-sm rounded-lg border border-red-100 flex items-center gap-2">
                <span className="font-bold">Error:</span> {error}
            </div>
        );
    }

    return (
        <div className="space-y-6">
            {/* Add/Edit Modal */}
            {(isAddingManual || editingEntry) && (
                <AddTournamentHistoryModal
                    athleteId={athleteId}
                    initialData={editingEntry || undefined}
                    onClose={() => {
                        setIsAddingManual(false);
                        setEditingEntry(null);
                    }}
                />
            )}

            {/* Header */}
            <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold text-slate-800">Tournament History</h3>
                <button
                    onClick={() => setIsAddingManual(true)}
                    className="flex items-center gap-1.5 text-sm font-medium text-blue-600 hover:text-blue-700 transition-colors"
                >
                    <Plus className="w-4 h-4" />
                    Add Manual Entry
                </button>
            </div>

            {/* Timeline */}
            <div className="relative border-l-2 border-slate-200 ml-3 space-y-6 pb-2">
                {history.map((entry, index) => (
                    <div key={entry.id || index} className="relative pl-6">
                        {/* Timeline dot */}
                        <div className={`absolute -left-[9px] top-1 h-4 w-4 rounded-full border-2 border-white shadow-sm ${entry.is_auto_generated ? 'bg-green-500' : 'bg-blue-500'
                            }`} />

                        {/* Entry content */}
                        <div className="flex flex-col gap-2">
                            {/* Tournament name and badge */}
                            <div className="flex items-start justify-between gap-2">
                                <div className="flex-1">
                                    <div className="flex items-center gap-2 flex-wrap">
                                        <span className="text-sm font-bold text-slate-900">{entry.tournament_name}</span>
                                        <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${entry.is_auto_generated
                                            ? 'bg-green-100 text-green-700'
                                            : 'bg-blue-100 text-blue-700'
                                            }`}>
                                            {entry.is_auto_generated ? 'Auto' : 'Manual'}
                                        </span>
                                    </div>

                                    {/* Date and location */}
                                    <div className="mt-1 flex flex-wrap items-center gap-3 text-xs text-slate-500">
                                        <div className="flex items-center gap-1">
                                            <Calendar className="w-3 h-3" />
                                            {entry.tournament_date}
                                        </div>
                                        {entry.tournament_location && (
                                            <div className="flex items-center gap-1">
                                                <MapPin className="w-3 h-3" />
                                                {entry.tournament_location}
                                            </div>
                                        )}
                                    </div>

                                    {/* Weight class and age category */}
                                    {(entry.weight_class || entry.age_category) && (
                                        <div className="mt-1.5 flex flex-wrap items-center gap-2">
                                            {entry.weight_class && (
                                                <span className="text-[10px] font-medium px-2 py-1 bg-slate-100 text-slate-700 rounded">
                                                    {entry.weight_class}
                                                </span>
                                            )}
                                            {entry.age_category && (
                                                <span className="text-[10px] font-medium px-2 py-1 bg-slate-100 text-slate-700 rounded flex items-center gap-1">
                                                    <Award className="w-3 h-3" />
                                                    {entry.age_category}
                                                </span>
                                            )}
                                        </div>
                                    )}
                                </div>

                                {/* Action buttons (only for manual entries) */}
                                {!entry.is_auto_generated && entry.id && (
                                    <div className="flex items-center gap-1">
                                        <button
                                            onClick={() => handleEdit(entry)}
                                            className="p-1.5 text-slate-400 hover:text-blue-500 hover:bg-blue-50 rounded transition-colors"
                                            title="Edit Entry"
                                        >
                                            <Edit2 size={12} />
                                        </button>
                                        <button
                                            onClick={() => handleDelete(entry.id!, entry.is_auto_generated || false)}
                                            className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded transition-colors"
                                            title="Delete Entry"
                                        >
                                            <Trash2 size={12} />
                                        </button>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                ))}

                {/* Empty state */}
                {history.length === 0 && (
                    <div className="pl-6 pt-1 text-sm text-slate-400 italic">
                        No tournament history recorded. Tournament participation will be automatically tracked when athletes are added to tournament rosters.
                    </div>
                )}
            </div>
        </div>
    );
};
