INSERT OR IGNORE INTO athletes (name, birthYear, gender, weight, rank, clubId, createdAt, updatedAt) VALUES
('Kenji Yamamoto', 1995, 'male', 73.5, 'Black (DAN 1)', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Maria Rodriguez', 2002, 'female', 63.0, 'Blue', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Liam O''Connell', 2004, 'male', 81.2, 'Orange', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sarah Chen', 2001, 'female', 57.5, 'Green', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('David Kim', 1999, 'male', 66.8, 'Brown', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Emma Watson', 2006, 'female', 52.0, 'Yellow', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lucas Silva', 2005, 'male', 90.0, 'White', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hana Sato', 1998, 'female', 48.0, 'Black (DAN 2)', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('James Smith', 2000, 'male', 100.0, 'Blue', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Olivia Jones', 2003, 'female', 70.0, 'Green', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hiroshi Tanahashi', 1985, 'male', 95.0, 'Black (DAN 4)', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kazuchika Okada', 1987, 'male', 105.0, 'Black (DAN 3)', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tetsuya Naito', 1988, 'male', 92.0, 'Black (DAN 2)', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kota Ibushi', 1989, 'male', 88.0, 'Black (DAN 1)', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tomohiro Ishii', 1980, 'male', 98.0, 'Brown', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Minoru Suzuki', 1975, 'male', 85.0, 'Black (DAN 6)', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Zack Sabre Jr', 1990, 'male', 78.0, 'Brown', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Will Ospreay', 1993, 'male', 82.0, 'Brown', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kenny Omega', 1983, 'male', 90.0, 'Black (DAN 3)', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bryan Danielson', 1981, 'male', 80.0, 'Black (DAN 5)', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
